POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Sumanth",
  "password": "Sanath143"
}

###
GET http://localhost:3000/

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Sanath",
  "password": "Sanath"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "Sanath",
  "oldPassword": "Sanath15",
  "newPassword": "Sanath"
}